import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Navbar/page";

export const metadata: Metadata = {
  title: "C & U Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
